##########---------uosc_history_menu Options---------##########
# https://github.com/Koopex/uosc_history_menu

# en: English
# zh: 简体中文
language=zh

##### 保存播放历史? ##### 
# yes/no
#--------------------------
##### Save history? #####
# yes/no
log=yes

##### 使用快捷键恢复播放 ##### 
# 按下快捷键来播放上次的视频
# 在"inpu_uosc.conf"中添加下面这一行(不带#)
# SPACE		script-binding uosc_history_menu/play_last_video		#! 继续播放
# 如果快捷键是空格,请设置space=yes,否则no
#-------------------------------------------------------------------------------------------
##### Resume playback with a shortcut key. ##### 
# Press the hotkey to play the last video.
# Insert the following entry into "input_uosc.conf" (without #)
# SPACE		script-binding uosc_history_menu/play_last_video		#! Resume Playback
# If the shortcut key is SPACE, set "space=yes"; otherwise "no".
space=yes

##### 打开mpv以后的动作 #####
# resume: 恢复上次播放的文件
# menu: 打开播放记录
# no: 什么也不做
#------------------------------------
##### mpv startup behavior #####
# resume: Play the last video.
# menu: Open history menu.
# no: None.
start_action=menu

##### 默认的播放记录过滤方式 #####
# 打开菜单时按左右方向键可以临时切换
# all: 全部
# deduplicated: 去重 (每个视频保留最后那次的记录)
# folders: 文件夹, 适合同时看多个剧 (如果文件夹是"Season 2"这种形式,则显示再上一层的文件夹)
#----------------------------------------------------------------------------------------------------
##### Default history filtering mode #####
# Press ←/→ arrow keys to temporarily switch views while menu is open.
# all: All.
# deduplicated: keep only the last record per video.
# folders: Show as parent folder; Good for following multiple tv-shows at the same time. When a folder follows the 'Season X' format, show as grandparent folder instead.
menu_filter=deduplicated

##### 提示本目录上次播放的视频 #####
# yes/no
#--------------------------------------------------------------
##### Mark which video was last played in this folde #####
# yes/no
last_video=yes

##### 标题后显示的内容 #####
# 只有过滤方式为去重时可以修改
# percent：播放进度%, 如：30%
# percent+duration: 播放进度%和视频总时长, 如：30% / 24:01
# position+duration：播放时长和总时长，如：07:10 / 24:01
#--------------------------------------------------------
##### Metadata appended to titles #####
# Applied only menu_filter=deduplicated
# percent：Playback progress (percentage)
# percent+duration: Playback progress and duration; Like "30% / 24:01"
# position+duration：Time played and duration; Like "07:10 / 24:01"
hint=position+duration

##### 开启流媒体播放记录? #####
# <yes/no>
#-------------------------------------------
##### Save history for "urls"? #####
# <yes/no>
log_url=no

##### 简化标题? #####
# <yes/no>
#----------------------------------------
##### Simplify title ?  #####
# <yes/no>
simplified_media_title=no

##### 屏蔽词 #####
# 如果简化效果不理想可以添加屏蔽词, 屏蔽词从长到短排列, 屏蔽词中的"-"和"."前面要加上"%"
#----------------------------------------
##### Blocked words #####
# If simplification results are unsatisfactory, add blocked words. Arrange blocked words from longest to shortest. For "-" and "." in blocked words, prefix them with "%".
blocked_words=Netflix,AMZN,Disney%+,Bilibili,YUV420P10,Multi%-Audio,1920x1080,Blu%-ray,ULTRAHD,2Audio,3Audio,4Audio,BluRay,bluray,WEB%-DL,TrueHD,DTS%-HD,REPACK,Atmos,BDrip,10bit,60FPS,60fps,H%.264,1080p,1080P,2160p,2160P,720P,720p,DoVi,IMAX,HDTV,x265,X265,H265,x264,X264,H264,HEVC,VC%-1,FLAC,DIY,EUR,DDP,DTS,HDR,UHD,AVC,AAC,AC3,4K,2%.0,5%.1,7%.1,DV,DD,HQ,MA

##### 记录文件存放路径 #####
#----------------------------------
##### Log path #####
log_path=/:dir%mpvconf%/uosc_history_menu.log
