##########---------uosc_history_menu 设置---------##########
# https://github.com/Koopex/uosc_history_menu

##### 可使用的快捷键 ##### 
# 在"inpu_uosc.conf"中添加下方内容(不带#)
# r			    script-binding uosc_history/toggle_menu		#! 播放记录
# Ctrl+r	    script-binding uosc_history/clear			#! 清空播放记录
# Ctrl+Alt+r	script-binding uosc_history/toggle_log		#! 启用/禁用 播放记录


# <en>: English
# <zh>: 中文
language=zh

##### 打开mpv以后的动作 #####
# <resume>: 恢复上次播放的文件
# <menu>: 打开播放记录
# <none>: 什么也不做
start_action=none

##### 提示本目录上次播放的视频 #####
# <yes/no>
resume_in_folder=no

##### 记录文件存放路径 #####
# /:dir%mpvconf%/ 表示mpv.conf所在文件夹
log_path=/:dir%mpvconf%/uosc_history.json

