# https://github.com/Koopex/uosc_history_menu

#==============[ 脚本设置 ]===============

# <zh>: 中文
# <en>: English
language=zh

#--------[ 打开mpv以后的动作 ]--------
# <resume>	恢复上次播放的文件
# <menu>	打开播放记录
# <none>	什么也不做
start_action=none

#-----------[ 文件夹续播 ]------------
#  当你打开某文件夹中的一个视频时，
#  如果同文件夹内有其他视频记录，
#  插件会弹出菜单询问你是否跳转续播。
# <yes>
# <no>
resume_in_folder=no

#-----------[ 条目标题 ]-------------
# <yes>	列表显示 文件名
# <no>	列表显示 媒体标题
filename=no

#---------[ 记录文件路径 ]-----------
# ~~home 表示mpv.conf所在文件夹
log_path = '~~home/uosc_history.json'

