##########---------uosc_history_menu 设置---------##########
# https://github.com/Koopex/uosc_history_menu

############ 可选快捷键 ############
# e				script-binding uosc_history/bookmarks	        #! 收藏夹  					
# Ctrl+e		script-binding uosc_history/add_bookmarks		#! 添加收藏								
# Ctrl+Alt+e	script-binding uosc_history/clear_bookmarks		#! 清空收藏夹		    				
# r				script-binding uosc_history/history	            #! 播放记录                         
# Ctrl+r		script-binding uosc_history/enable_history      #! 启用/禁用 播放记录														
# Ctrl+Alt+r    script-binding uosc_history/clear_history	    #! 清空播放记录

############ 可选按钮 ############
#button:history             播放记录
#button:bookmarks           收藏夹
#button:add_bookmarks       添加收藏

# <en>: English
# <zh>: 中文
language=zh

##### 打开mpv以后的动作 #####
# <resume>: 恢复上次播放的文件
# <menu>: 打开播放记录
# <none>: 什么也不做
start_action=none

##### 提示本目录上次播放的视频 #####
# <yes/no>
resume_in_folder=no

##### 记录文件存放路径 #####
# ~~home/ 表示mpv.conf所在文件夹
log_path=~~home/uosc_history.json

