##########---------uosc_history_menu配置---------##########
# https://github.com/Koopex/uosc_history_menu

##### 快捷键恢复播放 ##### 
# 可以绑定快捷键恢复上次播放的文件,需要在inpu_uosc.conf中添加下面这一行
# SPACE		script-message play_last_video		#! 继续播放
# 如果绑定为空格,请保持space=yes,其他按键设为space=no
space=yes

##### 打开mpv以后的动作 #####
# resume: 恢复上次播放的文件
# menu: 打开播放记录
# no: 什么也不做
start_action=menu

##### 默认的播放记录过滤方式 #####
# 打开菜单时按左右方向键可以临时切换
# all: 全部
# dry: 去重
# directory: 目录, 适合同时看多个剧
menu_filter=all

##### 提示本目录上次播放的视频 #####
#  <yes, no> 
last_video=yes

##### 标题后显示的内容 #####
# date： 播放日期时间, 如：[2025-03-05 03:48:43]
# position：播放时长, 如：07:10
# duration： 视频总时长, 如24:01
# percent： 播放进度%, 如：30%
# percent+duration: 播放进度%和视频总时长, 如：30% / 24:01
# position+duration：播放时长和总时长，如：07:10 / 24:01
# 当menu_filter为目录时, 显示当前文件在目录中的顺序, 如: 3/12
hint=position+duration

##### 流媒体播放记录 #####
# <yes, no>
log_url=no

##### 简化标题 #####
# <yes, no>
simplified_media_title=no

##### 屏蔽词 #####
# 如果简化效果不理想可以添加屏蔽词, 屏蔽词从长到短排列, 屏蔽词中的'-'和'.'前面要加上'%'
blocked_words=Netflix,AMZN,Disney%+,Bilibili,YUV420P10,Multi%-Audio,1920x1080,Blu%-ray,ULTRAHD,2Audio,3Audio,4Audio,BluRay,bluray,WEB%-DL,TrueHD,DTS%-HD,REPACK,Atmos,BDrip,10bit,60FPS,60fps,H%.264,1080p,1080P,2160p,2160P,720P,720p,DoVi,IMAX,HDTV,x265,X265,H265,x264,X264,H264,HEVC,VC%-1,FLAC,DIY,EUR,DDP,DTS,HDR,UHD,AVC,AAC,AC3,4K,2%.0,5%.1,7%.1,DV,DD,HQ,MA

##### 播放记录存放路径 #####
log_path=/:dir%mpvconf%/uosc_history_menu.log
