##########---------uosc_history_menu Options---------##########
# https://github.com/Koopex/uosc_history_menu

##### 可使用的快捷键 ##### 
# 在"inpu_uosc.conf"中添加下方内容(不带#)
# SPACE		script-binding uosc_history/resume			#! 继续播放
# r			script-binding uosc_history/toggle_menu		#! 播放记录
# Ctrl+r	script-binding uosc_history/clear			#! 清空播放记录
#------------------------------------------------------------------------------
##### Available Shortcuts ##### 
# Insert the following entries into "input_uosc.conf" (without #)
# SPACE		script-binding uosc_history/resume			#! Resume Playback
# r			script-binding uosc_history/toggle_menu		#! Playback History
# Ctrl+r	script-binding uosc_history/clear			#! Clear History

# <en>: English
# <zh>: 简体中文
language=en

##### 保存播放历史? ##### 
# <yes/no>
#--------------------------
##### Save history? #####
# <yes/no>
log=yes

##### 打开mpv以后的动作 #####
# <resume>: 恢复上次播放的文件
# <menu>: 打开播放记录
# <no>: 什么也不做
#------------------------------------
##### mpv startup behavior #####
# <resume>: Play the last video.
# <menu>: Open history menu.
# <no>: None.
start_action=menu

##### 默认的播放记录过滤方式 #####
# 打开菜单时按左右方向键可以临时切换
# <all>: 全部
# <dedup>: 去重 (每个视频保留最后那次的记录)
# <folders>: 文件夹, 适合同时看多个剧 (如果文件夹是"Season 2"这种形式,则显示再上一层的文件夹)
#----------------------------------------------------------------------------------------------------
##### Default history filtering mode #####
# Press ←/→ arrow keys to temporarily switch views while menu is open.
# <all>: All.
# <dedup>: keep only the last record per video.
# <folders>: Show as parent folder; Good for following multiple tv-shows at the same time. When a folder follows the 'Season X' format, show as grandparent folder instead.
filter=dedup

##### 提示本目录上次播放的视频 #####
# <yes/no>
#--------------------------------------------------------------
##### Notify the last played video in this folder #####
# <yes/no>
resume_in_folder=no

##### 记录文件存放路径 #####
#----------------------------------
##### Log path #####
log_path=/:dir%mpvconf%/uosc_history.json
