##########---------uosc_history_menu Options---------##########
# https://github.com/Koopex/uosc_history_menu

############ Available Shortcuts ############ 
# Insert the following entries into "input_uosc.conf" (without #)
# r			    script-binding uosc_history/toggle_menu		#! Playback History
# Ctrl+r	    script-binding uosc_history/clear			#! Clear History
# Ctrl+shift+r	script-binding uosc_history/toggle_log		#! Enable/Disable History

# <en>: English
# <zh>: 中文
language=en

##### Startup Action #####
# <resume>: Play the last video.
# <menu>: Open history menu.
# <none>: None.
start_action=none

##### Notify the last played video in this folder #####
# <yes/no>
resume_in_folder=no

##### Log path #####
# /:dir%mpvconf%/ is the mpv config directory.
log_path=/:dir%mpvconf%/uosc_history.json
