# https://github.com/Koopex/uosc_history_menu

#==================[ Script Settings ]===================

# <zh>: 中文
# <en>: English
language=zh

#------------------[ Startup Action ]------------------
# <resume>	Play the last media
# <menu>	Open history menu
# <none>	None
start_action=none

#--------------[ Resume in Same Folder ]---------------
#  When you open a video in a folder, 
#  if there are other video records in the same folder, 
#  the script will pop up a menu asking if you want to 
#  jump to resume playback.
# <yes>
# <no>
resume_in_folder=no

#-------------------[ Entry Title ]--------------------
# <yes>	Filename
# <no>	Media title
filename=no

#--------------------[ Log path ]----------------------
# ~~home is the mpv config directory
log_path = '~~home/uosc_history.json'

