# https://github.com/Koopex/uosc_history_menu

#================================[ Script Options ]=================================

# Language
# <zh>: Chinese
# <en>: English
language=zh

#------------------[ Startup Action ]------------------
# <resume>  Resume last played file
# <menu>    Open history menu on startup
# <none>    Do nothing
startup_action=none

#--------------[ Resume in Same Folder ]---------------
# When opening a file, if other videos in the same folder
# have playback history, prompt to resume one of them.
# <yes>
# <no>
resume_in_folder=no

#-------------------[ Title Source ]--------------------
# <yes>  Use filename
# <no>   Use media title
use_filename=no

#---------------[ Sort Search Results ]----------------
# <yes>  Sort by playback time
# <no>   Default order from uosc
search_sorting=no

#--------------------[ Data Path ]----------------------
# ~~/ refers to the mpv config directory
data_path=~~/uosc_history.json



#----------------------------------[ Shortcuts ]-------------------------------------
# r               script-binding uosc_history/history             #! Playback History
# Ctrl+r          script-binding uosc_history/enable_history      #! Toggle History
# Ctrl+Alt+r      script-binding uosc_history/clear_history       #! Clear History

# d               script-binding uosc_history/bookmarks           #! Bookmarks
# Ctrl+d          script-binding uosc_history/add_bookmarks       #! Add Bookmark
# Alt+d           script-binding uosc_history/toggle_quick_mark   #! Quick Bookmark
# Ctrl+Alt+d      script-binding uosc_history/clear_bookmarks     #! Clear Bookmarks
#-----------------------------------------------------------------------------------

#--------------[ uosc Buttons ]--------------
# button:history          Playback History
# button:bookmarks        Bookmarks
# button:add_bookmarks    Add Bookmark
#--------------------------------------------
#===================================================================================
